[package]
name = "bevy-sequential-actions"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["hikikones"]
description = "A Bevy library for executing actions in a sequence."
repository = "https://github.com/hikikones/bevy-sequential-actions"
homepage = "https://github.com/hikikones/bevy-sequential-actions"
keywords = ["bevy", "action", "sequence", "command"]
categories = ["game-development"]
readme = "README.md"

[dependencies]
bevy_ecs = "0.8"

[dev-dependencies]
shared = { path = "examples/shared" }
bevy = "0.8"
